In [2]:
import numpy as np

X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

# Add intercept
X = np.c_[np.ones(len(X)), X]

## β^​=(XTX)^-1XTy

In [3]:
beta_hat = np.linalg.inv(X.T @ X) @ X.T @ y
beta_hat

array([2.2, 0.6])

In [4]:
y_pred = X @ beta_hat

In [5]:
residuals = y - y_pred
n, p = X.shape

sigma_squared = (residuals @ residuals) / (n - p)
sigma = np.sqrt(sigma_squared)

In [6]:
x_new = np.array([1, 6])  # intercept + feature

mean = x_new @ beta_hat

In [9]:
X.T @ X

array([[ 5., 15.],
       [15., 55.]])

In [8]:
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.]])